// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniGuide.Data;

#nullable disable

namespace UniGuide.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniGuide.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("UniGuide.Models.AdmissionDeadLine", b =>
                {
                    b.Property<int>("DeadLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeadLineID"));

                    b.Property<DateTime>("AdmissionOpenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TestRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("UniversityID")
                        .HasColumnType("integer");

                    b.HasKey("DeadLineID");

                    b.HasIndex("ProgramID");

                    b.HasIndex("UniversityID");

                    b.ToTable("AdmissionDeadlines");
                });

            modelBuilder.Entity("UniGuide.Models.CareerPath", b =>
                {
                    b.Property<int>("CareerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CareerID"));

                    b.Property<string>("DemandLevel")
                        .HasColumnType("text");

                    b.Property<string>("IndustryType")
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxSalaryPKR")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinSalaryPKR")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.Property<string>("SkillRequired")
                        .HasColumnType("text");

                    b.HasKey("CareerID");

                    b.HasIndex("ProgramID");

                    b.ToTable("CareerPaths");
                });

            modelBuilder.Entity("UniGuide.Models.Program", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgramID"));

                    b.Property<int>("DurationYears")
                        .HasColumnType("integer");

                    b.Property<decimal>("FeePerSemester")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("MinMeritPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("ProgramName")
                        .HasColumnType("text");

                    b.Property<string>("RequiredInterGroup")
                        .HasColumnType("text");

                    b.Property<string>("Shift")
                        .HasColumnType("text");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.Property<int>("UniversityID")
                        .HasColumnType("integer");

                    b.HasKey("ProgramID");

                    b.HasIndex("UniversityID");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("UniGuide.Models.QuizQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionID"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("OptionA")
                        .HasColumnType("text");

                    b.Property<string>("OptionB")
                        .HasColumnType("text");

                    b.Property<string>("OptionC")
                        .HasColumnType("text");

                    b.Property<string>("OptionD")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionID");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("UniGuide.Models.SavedUniversity", b =>
                {
                    b.Property<int>("SavedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SavedID"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentID")
                        .HasColumnType("integer");

                    b.Property<int>("UniversityID")
                        .HasColumnType("integer");

                    b.HasKey("SavedID");

                    b.HasIndex("ProgramID");

                    b.HasIndex("StudentID");

                    b.HasIndex("UniversityID");

                    b.ToTable("SavedUniversities");
                });

            modelBuilder.Entity("UniGuide.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentID"));

                    b.Property<decimal>("BudgetPerSemester")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InterGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("InterMarksPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UniGuide.Models.StudentQuizResult", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResultID"));

                    b.Property<string>("InterestProfile")
                        .HasColumnType("text");

                    b.Property<string>("RecommendedField")
                        .HasColumnType("text");

                    b.Property<string>("ScoreBreakDown")
                        .HasColumnType("text");

                    b.Property<int>("StudentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ResultID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentQuizResults");
                });

            modelBuilder.Entity("UniGuide.Models.University", b =>
                {
                    b.Property<int>("UniversityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UniversityID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstablishedYear")
                        .HasColumnType("integer");

                    b.Property<int>("HECRanking")
                        .HasColumnType("integer");

                    b.Property<bool>("HasHostel")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTransport")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UniversityID");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("UniGuide.Models.AdmissionDeadLine", b =>
                {
                    b.HasOne("UniGuide.Models.Program", "Program")
                        .WithMany("AdmissionDeadlines")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGuide.Models.University", "University")
                        .WithMany("AdmissionDeadLines")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniGuide.Models.CareerPath", b =>
                {
                    b.HasOne("UniGuide.Models.Program", "Program")
                        .WithMany("CareerPaths")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("UniGuide.Models.Program", b =>
                {
                    b.HasOne("UniGuide.Models.University", "University")
                        .WithMany("Programs")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniGuide.Models.SavedUniversity", b =>
                {
                    b.HasOne("UniGuide.Models.Program", "Program")
                        .WithMany("SavedUniversities")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniGuide.Models.Student", "Student")
                        .WithMany("SavedUniversities")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniGuide.Models.University", "University")
                        .WithMany("SavedUniversities")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Student");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniGuide.Models.StudentQuizResult", b =>
                {
                    b.HasOne("UniGuide.Models.Student", "Student")
                        .WithMany("QuizResults")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniGuide.Models.Program", b =>
                {
                    b.Navigation("AdmissionDeadlines");

                    b.Navigation("CareerPaths");

                    b.Navigation("SavedUniversities");
                });

            modelBuilder.Entity("UniGuide.Models.Student", b =>
                {
                    b.Navigation("QuizResults");

                    b.Navigation("SavedUniversities");
                });

            modelBuilder.Entity("UniGuide.Models.University", b =>
                {
                    b.Navigation("AdmissionDeadLines");

                    b.Navigation("Programs");

                    b.Navigation("SavedUniversities");
                });
#pragma warning restore 612, 618
        }
    }
}
